meta_title: "Shared Forests - Offrez des arbres !"
meta_description: "Offrez des arbres et partagez une forêt en Amazonie !"
meta_image: "meta-banner.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@_Conscients" # indispensable pour les Twitter Cards
